### ISSUE TITLE
Add state to load timezone data into MySQL

### ISSUE THREAD

**Issue by BigglesZX** [BigglesZX/salt-common#4]
Equivalent of:

* `sudo apt-get install tzdata`
* `sudo dpkg-reconfigure tzdata`
* Select appropriate timezone
* `mysql_tzinfo_to_sql /usr/share/zoneinfo | mysql -u root -p mysql`
* `service mysql restart`

**Comment by holms** [comment]
@BigglesZX  any progress on this?

**Comment by BigglesZX** [comment]
@holms Hi there - I'm not completely sure that the tz data can be loaded completely automatically in a state, but I can look into it if you like? Are you using these states yourself? Thanks for writing.

**Comment by holms** [comment]
Yeah I'm using some of them. I've came across idea with `cmd.run` and `unless`. Probably will put this to mysql-formula. First of all timezones installed by default, so all is left it's to perform `mysql_tzinfo_to_sql /usr/share/zoneinfo | mysql -u root -p mysql` with `cmd.run`and check with `unless` if that table timezones already exist in `mysql` database. :)

**Comment by BigglesZX** [comment]
@holms That's very helpful, thank you. I'll try to look at this in the next couple of days.

**Comment by BigglesZX** [comment]
@holms That's now done - seems to work on my side! New state is [here](https://github.com/BigglesZX/salt-common/tree/master/salt/states/mysql-tzdata).

You'll need to add it to your project's `top.sls` too as per [here](https://github.com/BigglesZX/Vagrant-template/commit/f2229b102b757f769e97480df50ea09ab6506663).

Hope that works for you too - let me know if you have any issues. I wasn't able to figure out how to run the load command conditionally by checking if the table already existed, so if you know how to do that feel free to submit a PR!
